// Run with: node scripts/fetch-prices.js
//
// Requires a free stooq.com API key (one-time setup):
//   1. Open https://stooq.com/q/d/?s=aapl.us&get_apikey in a browser
//   2. Solve the captcha
//   3. Copy the apikey value from the download link shown on that page
//   4. Set it as an environment variable:
//        $env:STOOQ_API_KEY = "your_key_here"   (PowerShell)
//        export STOOQ_API_KEY=your_key_here      (bash)
//   5. Run: node scripts/fetch-prices.js
//
// The generated data/prices.js is committed to the repo — you only need to
// re-run this script when adding new years or stocks.

const https = require('https');
const fs    = require('fs');
const path  = require('path');

const API_KEY = process.env.STOOQ_API_KEY;
if (!API_KEY) {
  console.error('Error: STOOQ_API_KEY environment variable is not set.');
  console.error('See the instructions at the top of this file.');
  process.exit(1);
}

const STOCKS_US = [
  { stooq: 'aapl.us'  },
  { stooq: 'msft.us'  },
  { stooq: 'amzn.us'  },
  { stooq: 'googl.us' },
  { stooq: 'meta.us'  },
  { stooq: 'tsla.us'  },
  { stooq: 'nvda.us'  },
  { stooq: 'jpm.us'   },
  { stooq: 'jnj.us'   },
  { stooq: 'xom.us'   },
  { stooq: 'v.us'     },
  { stooq: 'wmt.us'   },
  { stooq: 'pg.us'    },
  { stooq: 'unh.us'   },
  { stooq: 'nflx.us'  },
];

const STOCKS_UK = [
  { stooq: 'azn.uk'  },
  { stooq: 'shel.uk' },
  { stooq: 'hsba.uk' },
  { stooq: 'ulvr.uk' },
  { stooq: 'rio.uk'  },
  { stooq: 'bp.uk'   },
  { stooq: 'gsk.uk'  },
  { stooq: 'dge.uk'  },
  { stooq: 'barc.uk' },
  { stooq: 'rr.uk'   },
];

const YEARS = [2020, 2021, 2022, 2023, 2024];

function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return fetchUrl(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

function parseCSV(csvText) {
  const lines = csvText.trim().split('\n');
  const dates  = [];
  const prices = [];
  // stooq returns newest-first; reverse to get oldest-first
  for (let i = lines.length - 1; i >= 1; i--) {
    const parts = lines[i].split(',');
    if (parts.length >= 5) {
      const date  = parts[0].trim();
      const close = parseFloat(parts[4]);
      if (date && !isNaN(close) && close > 0) {
        dates.push(date);
        prices.push(+close.toFixed(2));
      }
    }
  }
  return { dates, prices };
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function main() {
  const all = [...STOCKS_US, ...STOCKS_UK];
  const result = {};
  let ok = 0, skipped = 0, failed = 0;

  for (const stock of all) {
    result[stock.stooq] = {};
    for (const year of YEARS) {
      const d1  = `${year}0101`;
      const d2  = `${year}1231`;
      const url = `https://stooq.com/q/d/l/?s=${stock.stooq}&d1=${d1}&d2=${d2}&i=d&apikey=${API_KEY}`;
      process.stdout.write(`  ${stock.stooq} ${year} ... `);
      try {
        const csv = await fetchUrl(url);
        if (csv.includes('apikey')) {
          // stooq returned the error/instructions page
          console.log('FAIL: invalid or expired API key');
          failed++;
          break; // no point continuing with a bad key
        }
        const { dates, prices } = parseCSV(csv);
        if (prices.length < 2) {
          console.log(`skip (${prices.length} rows)`);
          skipped++;
        } else {
          result[stock.stooq][String(year)] = { dates, prices };
          console.log(`ok (${prices.length} days)`);
          ok++;
        }
      } catch (err) {
        console.log(`FAIL: ${err.message}`);
        failed++;
      }
      await sleep(400); // polite rate limiting
    }
  }

  const outDir  = path.join(__dirname, '..', 'data');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir);
  const outPath = path.join(outDir, 'prices.js');
  const js = [
    '// Auto-generated by scripts/fetch-prices.js — do not edit by hand.',
    '// To refresh: node scripts/fetch-prices.js  (requires STOOQ_API_KEY env var)',
    `window.HISTORICAL_PRICES = ${JSON.stringify(result)};`,
    '',
  ].join('\n');

  fs.writeFileSync(outPath, js, 'utf8');
  const kb = (fs.statSync(outPath).size / 1024).toFixed(0);
  console.log(`\nDone. ok=${ok} skipped=${skipped} failed=${failed}`);
  console.log(`Wrote ${outPath} (${kb} KB)`);
}

main().catch(err => { console.error(err); process.exit(1); });
